export function classNames(...classes: unknown[]): string {
  return classes.filter(Boolean).join(' ')
}

export const locales = {
  af: 'Afrikaans',
  am: 'Amharic',
  ar: 'Arabic',
  as: 'Assamese',
  az: 'Azerbaijani',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bn: 'Bengali Bangla',
  bs: 'Bosnian',
  ca: 'Catalan Valencian',
  cs: 'Czech',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  el: 'Modern Greek',
  en: 'English',
  es: 'Spanish Castilian',
  et: 'Estonian',
  eu: 'Basque',
  fa: 'Persian',
  fi: 'Finnish',
  fil: 'Filipino Pilipino',
  fr: 'French',
  gl: 'Galician',
  gsw: 'Swiss German Alemannic Alsatian',
  gu: 'Gujarati',
  he: 'Hebrew',
  hi: 'Hindi',
  hr: 'Croatian',
  hu: 'Hungarian',
  hy: 'Armenian',
  id: 'Indonesian',
  is: 'Icelandic',
  it: 'Italian',
  ja: 'Japanese',
  ka: 'Georgian',
  kk: 'Kazakh',
  km: 'Khmer Central Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  ky: 'Kirghiz Kyrgyz',
  lo: 'Lao',
  lt: 'Lithuanian',
  lv: 'Latvian',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mr: 'Marathi',
  ms: 'Malay',
  my: 'Burmese',
  nb: 'Norwegian Bokmål',
  ne: 'Nepali',
  nl: 'Dutch Flemish',
  no: 'Norwegian',
  or: 'Oriya',
  pa: 'Panjabi Punjabi',
  pl: 'Polish',
  ps: 'Pushto Pashto',
  pt: 'Portuguese',
  ro: 'Romanian Moldavian Moldovan',
  ru: 'Russian',
  si: 'Sinhala Sinhalese',
  sk: 'Slovak',
  sl: 'Slovenian',
  sq: 'Albanian',
  sr: 'Serbian',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tl: 'Tagalog',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  vi: 'Vietnamese',
  zh: 'Chinese',
  zu: 'Zulu'
}
export type TabType = 'presets' | 'build-your-own' | 'reference'
export const tabs: Record<TabType, string> = {
  presets: 'Presets',
  'build-your-own': 'Build Your Own',
  reference: 'Reference'
}
